### ISSUE TITLE
change to normal 

### ISSUE THREAD

**Issue by needonature** [paveethranswam/Diet-Nutrition-and-Foods-recommendation-for-Cancer-Patients-and-extend-this-to-build-as-application#10]
Change all nested one line python code (marked with "change to normal ") into more readable (easily to understand) multiple lines code

**Comment by paveethranswam** [comment]
I have changed one of those three marking to normal code. I think it is better to keep the other two as one-line code - it best works that way. And also I have added explanation for those two one-line codes so that we can understand what is happening there.
